package launcher

import (
	"errors"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"shulker.sh/shulker/internal/fsutil"
	"shulker.sh/shulker/internal/instance"
)

// HookKind names a launcher slot, and is also the subcommand the generated script runs.
type HookKind string

const (
	HookPreLaunch HookKind = "pre-launch"
	HookPostExit  HookKind = "post-exit"
)

const hookMissingShulker = "shulker isn't installed, get it at shulker.sh to receive pack updates"

// Hook is one generated script: which slot it fills and what it has to run.
type Hook struct {
	// Dir is the directory shulker syncs into, which is where .shulker/ lives.
	Dir  string
	Kind HookKind
	// Shulker is the binary recorded in settings.shulker. The script prefers it and falls back to
	// PATH, because a launcher opened from the Dock has neither the shell's PATH nor a terminal.
	Shulker string
	// Adopted is the command shulker found in the launcher's slot. It runs first and a non-zero exit
	// from it still aborts the launch, exactly as it did before shulker owned the slot.
	Adopted string
	// Tokens are the launcher's own instance variables, which it stops substituting once the adopted
	// command lives inside this script.
	Tokens map[string]string
	// Deadline bounds the refresh and makes the script pass shulker's exit status on, which is the
	// only way a message reaches the player. Only GDLauncher sets one.
	Deadline string
}

// HookPath is where a hook's script goes. Only the running OS's shape is ever written; the other is
// removed, because a launcher slot holds one command and that command names one of these.
func HookPath(dir string, kind HookKind) string { return hookPath(dir, kind, runtime.GOOS) }

func hookPath(dir string, kind HookKind, goos string) string {
	name := string(kind)
	if goos == "windows" {
		name += ".cmd"
	}
	return filepath.Join(dir, instance.Dir, name)
}

// WriteHook writes the script for the running OS and removes the other OS's, so reconcile owns
// every script under .shulker/.
func WriteHook(h Hook) error {
	return writeHook(h, runtime.GOOS)
}

func writeHook(h Hook, goos string) error {
	if err := os.MkdirAll(filepath.Join(h.Dir, instance.Dir), 0o755); err != nil {
		return err
	}
	if err := removeHookFile(otherPath(h.Dir, h.Kind, goos)); err != nil {
		return err
	}
	return fsutil.Write(hookPath(h.Dir, h.Kind, goos), []byte(hookBody(h, goos)))
}

// RemoveHook drops both shapes of a hook's script.
func RemoveHook(dir string, kind HookKind) error {
	for _, goos := range []string{"unix", "windows"} {
		if err := removeHookFile(hookPath(dir, kind, goos)); err != nil {
			return err
		}
	}
	return nil
}

func otherPath(dir string, kind HookKind, goos string) string {
	if goos == "windows" {
		return hookPath(dir, kind, "unix")
	}
	return hookPath(dir, kind, "windows")
}

func removeHookFile(path string) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func hookBody(h Hook, goos string) string {
	if goos == "windows" {
		return hookCmd(h)
	}
	return hookSh(h)
}

// hookSh derives the instance directory from the script's own location rather than embedding it, so
// a moved instance keeps working for the same reason the slot command uses the launcher's token.
func hookSh(h Hook) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by shulker. Edits are lost on the next sync; turn the hook off in\n")
	b.WriteString("# .shulker/instance.json instead.\n\n")
	b.WriteString(`dir=$(cd "$(dirname "$0")/.." && pwd) || exit 0` + "\n\n")
	if h.Adopted != "" {
		for _, name := range slices.Sorted(maps.Keys(h.Tokens)) {
			fmt.Fprintf(&b, "%s=%s; export %s\n", name, shSingleQuote(h.Tokens[name]), name)
		}
		b.WriteString(h.Adopted + "\n")
		b.WriteString("adopted=$?\n")
		b.WriteString(`if [ "$adopted" -ne 0 ]; then exit "$adopted"; fi` + "\n\n")
	}
	fmt.Fprintf(&b, "shulker=%s\n", shSingleQuote(h.Shulker))
	b.WriteString(`if [ ! -x "$shulker" ]; then shulker=$(command -v shulker || true); fi` + "\n")
	b.WriteString(`if [ -z "$shulker" ]; then` + "\n")
	fmt.Fprintf(&b, "\techo %s >&2\n", shSingleQuote(hookMissingShulker))
	b.WriteString("\texit 0\nfi\n\n")
	if h.Deadline == "" {
		fmt.Fprintf(&b, "\"$shulker\" hook %s -C \"$dir\" || true\nexit 0\n", h.Kind)
		return b.String()
	}
	// Only a paused update leaves shulker non-zero, so passing the status on can't abort a launch
	// over an ordinary sync failure.
	fmt.Fprintf(&b, "\"$shulker\" hook %s -C \"$dir\" --deadline %s\nexit $?\n", h.Kind, h.Deadline)
	return b.String()
}

func hookCmd(h Hook) string {
	var b strings.Builder
	b.WriteString("@echo off\r\n")
	b.WriteString("rem Generated by shulker. Edits are lost on the next sync; turn the hook off in\r\n")
	b.WriteString("rem .shulker\\instance.json instead.\r\n\r\n")
	b.WriteString(`for %%i in ("%~dp0..") do set "dir=%%~fi"` + "\r\n\r\n")
	if h.Adopted != "" {
		for _, name := range slices.Sorted(maps.Keys(h.Tokens)) {
			fmt.Fprintf(&b, "set \"%s=%s\"\r\n", name, h.Tokens[name])
		}
		b.WriteString(h.Adopted + "\r\n")
		b.WriteString("if errorlevel 1 exit /b %errorlevel%\r\n\r\n")
	}
	fmt.Fprintf(&b, "set \"shulker=%s\"\r\n", h.Shulker)
	b.WriteString(`if not exist "%shulker%" set "shulker=shulker"` + "\r\n\r\n")
	if h.Deadline == "" {
		fmt.Fprintf(&b, "\"%%shulker%%\" hook %s -C \"%%dir%%\"\r\nexit /b 0\r\n", h.Kind)
		return b.String()
	}
	fmt.Fprintf(&b, "\"%%shulker%%\" hook %s -C \"%%dir%%\" --deadline %s\r\nexit /b %%errorlevel%%\r\n", h.Kind, h.Deadline)
	return b.String()
}

func shSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
