package launcher

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"shulker.sh/shulker/internal/fsutil"
	"shulker.sh/shulker/internal/instance"
)

// Shim is the file a Minecraft Launcher profile's javaDir names. The launcher execs it with the
// game's whole argument list, in an environment holding almost nothing, so both paths it needs are
// absolute and recorded in it rather than looked up.
type Shim struct {
	// Dir is the game directory, which is where .shulker/ lives.
	Dir string
	// Shulker is the binary recorded in settings.shulker. The shim hands the launch to it, and runs
	// Java itself when that binary is gone, so a deleted shulker costs the player updates, not the
	// game.
	Shulker string
	// Java is the Java to run without shulker: settings.java when set, else resolved.java.
	Java string
}

// ShimSupported reports whether this OS has a shim to write. A Windows profile keeps the launcher's
// own Java, because a script can't stand in for Java there: it needs a GUI-subsystem executable,
// which shulker doesn't carry yet.
func ShimSupported() bool { return runtime.GOOS != "windows" }

// ShimPath is the file a profile's javaDir names.
func ShimPath(dir string) string { return shimPath(dir, runtime.GOOS) }

func shimPath(dir, goos string) string {
	name := "java"
	if goos == "windows" {
		name = "javaw.exe"
	}
	return filepath.Join(dir, instance.Dir, name)
}

// IsShulkerShim reports whether a profile's javaDir is one shulker wrote, which is how reconcile
// tells its own value from the Java a player chose.
func IsShulkerShim(javaDir string) bool {
	for _, sep := range []string{"/", `\`} {
		if strings.HasSuffix(javaDir, instance.Dir+sep+"java") || strings.HasSuffix(javaDir, instance.Dir+sep+"javaw.exe") {
			return true
		}
	}
	return false
}

// WriteShim writes the shim and makes it executable, since the launcher runs it directly.
func WriteShim(s Shim) error {
	path := ShimPath(s.Dir)
	if err := os.MkdirAll(filepath.Join(s.Dir, instance.Dir), 0o755); err != nil {
		return err
	}
	if err := fsutil.Write(path, []byte(shimSh(s))); err != nil {
		return err
	}
	return os.Chmod(path, 0o755)
}

// RemoveShim drops both shapes of the shim, for a switch turned off or an instance unlinked.
func RemoveShim(dir string) error {
	for _, goos := range []string{"unix", "windows"} {
		if err := os.Remove(shimPath(dir, goos)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

// shimSh names the instance with -C because the launcher's version check runs the shim with no
// --gameDir in the argv, and passes the argv on after -- because it carries the session token and
// belongs to Java alone.
func shimSh(s Shim) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by shulker. Edits are lost on the next sync; turn the hooks off in\n")
	b.WriteString("# .shulker/instance.json instead.\n\n")
	b.WriteString(`dir=$(cd "$(dirname "$0")/.." && pwd)` + "\n")
	fmt.Fprintf(&b, "shulker=%s\n", shSingleQuote(s.Shulker))
	fmt.Fprintf(&b, "java=%s\n\n", shSingleQuote(s.Java))
	b.WriteString(`if [ -n "$dir" ] && [ -x "$shulker" ]; then` + "\n")
	b.WriteString("\texec \"$shulker\" hook wrap -C \"$dir\" -- \"$@\"\nfi\n\n")
	b.WriteString(`exec "$java" "$@"` + "\n")
	return b.String()
}
